# Generated by Django 3.2.4 on 2021-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
